[#sm3-algorithm]
= SM3 Hash Algorithm

The SM3 Cryptographic Hash Algorithm <<GBT.32905-2016>> is an iterative hash
function designed by Xiaoyun Wang et al., published by <<OSCCA>> as an
alternative to SHA-2 <<NIST.FIPS.180-4>>.

It was first published by the OSCCA in public in 2010 <<SM3>>, then published
in the OSCCA standard <<GMT-0004-2012>> in 2012, published as a Chinese National
Standard as <<GBT.32905-2016>> in 2016, and included in the <<ISO.IEC.10118-3>>
standard in 2017.

The algorithm is designed to be used for commercial cryptographic applications
including, but not limited to:

* digital signatures and their verification
* message authentication code generation and their verification
* generation of random numbers

SM3 has a Merkle-Damgard construction and is similar to SHA-2
<<NIST.FIPS.180-4>> of the MD4 <<RFC6150>> family, with the addition of several
strengthening features including a more complex step function and stronger
message dependency than SHA-256 <<SM3-Boomerang>>.

// TODO: add reference to new draft

SM3 produces an output hash value of 256 bits long, based on 512-bit
input message blocks <<GBT.32905-2016>>, on input lengths up to $$2^(m)$$.

The specification of SM3 is described in <<GBT.32905-2016>>, <<SM3>> and
<<I-D.shen-sm3-hash>>.

